[pytest]
filterwarnings =
    ignore::DeprecationWarning:crewai.*
    ignore::DeprecationWarning:opentelemetry.*
    ignore::DeprecationWarning:pydantic.*
    ignore::_pytest.warning_types.PytestReturnNotNoneWarning
    ignore::DeprecationWarning:akshare.*